##CREATE BARANG
POST http://localhost:3001/barang
Content-Type: application/json

{
    "NamaBarang": "Susu Ultra Aini Diah",
    "Satuan": "Pcs",
    "HargaSatuan": 5000.00,
    "Stok": 100
}

###update barang
PATCH http://localhost:3001/barang/4
Content-Type: application/json

{
    "HargaSatuan": 4000.00
}

### Find All
GET http://localhost:3001/barang

### Find One
GET http://localhost:3001/barang/4

### Delete
DELETE http://localhost:3001/barang/5

### Create KASIR
POST http://localhost:3001/kasir
Content-Type: application/json

{
    "Nama": "Falaah",
    "HP": "085237567887"
}

###update KASIR
PATCH http://localhost:3001/kasir/1
Content-Type: application/json

{
    "HP": "08211524033444"
}

### Find All
GET http://localhost:3001/kasir

### Find One
GET http://localhost:3001/kasir/1

### Delete
DELETE http://localhost:3001/kasir/3

### Create TENAN
POST http://localhost:3001/tenan
Content-Type: application/json

{
    "NamaTenan": "Dream",
    "HP": "081234547289"
}


###update TENAN
PATCH http://localhost:3001/tenan/1
Content-Type: application/json

{
    "HP": "08211524033444"
}

### Find All
GET http://localhost:3001/tenan

### Find One
GET http://localhost:3001/tenan/1

### Delete
DELETE http://localhost:3001/tenan/3

### Create NOTA
POST http://localhost:3001/nota
Content-Type: application/json

{
    "KodeTenan": 3,
    "KodeKasir": 1,
    "TglNota": "2023-11-29",
    "JamNota": "12:30:00",
    "JumlahBelanja": 45000.00,
    "Diskon": 0,
    "Total": 45000.00
}

### Find All
GET http://localhost:3001/nota

### Find One
GET http://localhost:3001/nota/1

### Delete
DELETE http://localhost:3001/nota/2

### CREATE BARANG NOTA
POST http://localhost:3001/barangNota
Content-Type: application/json

{
    "KodeNota": 1,
    "KodeBarang": 1,
    "JumlahBarang": 5,
    "HargaSatuan": 20000.00,
    "Jumlah": 100000.00
}

### Find All
GET http://localhost:3001/barangNota

### Find One
GET http://localhost:3001/barangNota/1

### Delete
DELETE http://localhost:3001/barangNota/1/1






